import "./styles.css";
import { academyCourses, exercises, meals, missionTemplates } from "./data/catalog.js";
import { achievements, assistantRules, attributes, onboardingSteps, storeItems } from "./data/content.js";
import { backend } from "./services/backend.js";
import {
  addMissionLocal, arenaDuelLocal, closeDayLocal, completeDungeonLocal, completeLessonLocal,
  completeMissionLocal, completePenaltyLocal, confirmLocalPlan, ensureDailyState, exerciseById,
  importRoutineLocal, loadLocalState, logMealLocal, logWorkoutLocal, mealById, purchaseLocal,
  replaceDraftExercise, replaceDraftMeal, replacePlanExercise, replacePlanMeal, resetLocalState,
  saveAvatarLocal, saveLocalState, saveNoteLocal, savePlanDraft, setGuildLocal, today, updateMissionLocal
} from "./services/local-store.js";

let state = ensureDailyState(loadLocalState());
let currentView = "inicio";
let session = null;
const demoAccess = String(import.meta.env.VITE_DEMO_FULL_ACCESS ?? "true") === "true";
const asset = name => `${import.meta.env.BASE_URL}assets/${name}`;
const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]);
const dayNumber = () => ((new Date().getDay() + 6) % 7) + 1;
const isDone = mission => mission?.completedOn?.includes(today());
const fullAccess = () => Boolean(state.profile.premium || (!backend.configured && demoAccess));
const getDraft = () => state.onboarding.draft || {};

function toast(message, danger = false) {
  const node = document.querySelector("#toast");
  node.textContent = message; node.classList.toggle("danger", danger); node.hidden = false;
  clearTimeout(toast.timer); toast.timer = setTimeout(() => { node.hidden = true; }, 3200);
}

function progress() {
  const daily = state.missions.filter(mission => mission.weekdays?.includes(dayNumber()));
  const done = daily.filter(isDone).length;
  return { daily, done, total: daily.length, percent: daily.length ? Math.round(done / daily.length * 100) : 0 };
}

function saveDraft(patch) {
  state.onboarding.draft = { ...getDraft(), ...patch };
  saveLocalState(state);
}

function welcomeView() {
  return `<section class="welcome-screen">
    <img src="${asset("hero-awakening.webp")}" alt="Portal de energía en un paisaje oscuro" />
    <div class="welcome-shade"></div><div class="welcome-copy"><span class="system-mark">G30</span>
      <p class="eyebrow">TU VIDA REAL. UN PLAN QUE PODÉS CUMPLIR.</p><h1>Tu transformación<br/>empieza con una decisión.</h1>
      <p>No necesitás saber entrenar ni comer perfecto. Respondé una evaluación breve, revisá cada parte y activá un plan de 30 días construido para tu realidad.</p>
      <div class="welcome-points"><span>✓ Misiones diarias</span><span>✓ Rutina progresiva</span><span>✓ Comidas simples</span></div>
      <button class="primary large" id="start-evaluation">COMENZAR EVALUACIÓN <b>→</b></button><small>Tarda entre 3 y 5 minutos. Nada se activa sin tu confirmación.</small>
    </div></section>`;
}

const option = (value, label, checked = false) => `<label class="choice"><input type="radio" name="value" value="${esc(value)}" ${checked ? "checked" : ""}/><span>${esc(label)}</span></label>`;
const goalOptions = ["Ganar fuerza y músculo", "Bajar grasa", "Mejorar condición", "Crear constancia"];

function assessmentForm(step) {
  const draft = getDraft();
  if (step === 0) return `<div class="assessment-intro"><small>IDENTIDAD</small><h2>¿Quién va a empezar este plan?</h2><p>Usamos estos datos sólo para organizar tu experiencia y orientar porciones. No reemplazan una evaluación médica.</p></div>
    <div class="form assessment-fields"><label>¿Cómo querés que te llamemos?<input name="displayName" required maxlength="40" value="${esc(draft.displayName || "")}" placeholder="Tu nombre"/></label><div class="form-row triple"><label>Edad<input name="age" type="number" min="14" max="100" value="${draft.age || 25}"/></label><label>Altura (cm)<input name="height" type="number" min="120" max="230" value="${draft.height || 175}"/></label><label>Peso (kg)<input name="weight" type="number" min="35" max="300" step=".1" value="${draft.weight || 75}"/></label></div><label>Tu objetivo principal<select name="goal">${goalOptions.map(value => `<option ${draft.goal === value ? "selected" : ""}>${value}</option>`).join("")}</select></label></div>`;
  if (step === 1) return `<div class="assessment-intro"><small>CONTEXTO REAL</small><h2>¿Cómo es un día normal?</h2><p>El plan tiene que entrar en tu agenda actual, no en una vida imaginaria.</p></div><div class="question-block"><h3>¿Cuánto te movés en tu trabajo?</h3><div class="choice-grid">${["Sedentario","Mixto","Activo","Muy físico"].map(value => option(value, value, (draft.workActivity || "Sedentario") === value)).join("")}</div></div><div class="form-row"><label>Horas de sueño habituales<input name="sleepHours" type="number" min="3" max="12" step=".5" value="${draft.sleepHours || 7}"/></label><label>Tiempo diario disponible<select name="dailyTime">${["20–30 min","30–45 min","45–60 min","Más de 60 min"].map(value => `<option ${draft.dailyTime === value ? "selected" : ""}>${value}</option>`).join("")}</select></label></div><label class="range-label">Estrés de esta semana <b id="stress-value">${draft.stress || 5}/10</b><input name="stress" type="range" min="1" max="10" value="${draft.stress || 5}"/></label>`;
  if (step === 2) return `<div class="assessment-intro"><small>ENTRENAMIENTO</small><h2>¿Qué podés hacer de verdad?</h2><p>Vas a ver todos los ejercicios antes de activar el plan y podrás reemplazarlos.</p></div><div class="question-block"><h3>Tu experiencia actual</h3><div class="choice-grid">${["Estoy empezando","Entrené antes","Entreno actualmente"].map(value => option(value, value, (draft.experience || "Estoy empezando") === value)).join("")}</div></div><div class="form-row"><label>Días por semana<input name="trainingDays" type="number" min="2" max="5" value="${draft.trainingDays || 3}"/></label><label>Lugar<select name="place">${["En casa","Gimnasio","Ambos"].map(value => `<option ${draft.place === value ? "selected" : ""}>${value}</option>`).join("")}</select></label></div><label>Equipo disponible<input name="equipment" value="${esc(draft.equipment || "")}" placeholder="Ej.: mancuernas, bandas, gimnasio completo"/></label><label>Lesiones, dolores o movimientos que debamos evitar<textarea name="limitations" placeholder="Si hay dolor o una lesión, consultá a un profesional.">${esc(draft.limitations || "")}</textarea></label>`;
  if (step === 3) return `<div class="assessment-intro"><small>ALIMENTACIÓN</small><h2>Comidas simples, no una dieta imposible.</h2><p>Evaluamos hábitos, posibilidades y preferencias. No pretendemos medir conocimiento nutricional con preguntas artificiales.</p></div><div class="form-row"><label>Comidas por día<select name="mealCount">${[3,4,5].map(value => `<option ${Number(draft.mealCount || 4) === value ? "selected" : ""}>${value}</option>`).join("")}</select></label><label>Tiempo para cocinar<select name="cookingTime">${["Menos de 15 min","15–30 min","30–45 min"].map(value => `<option ${draft.cookingTime === value ? "selected" : ""}>${value}</option>`).join("")}</select></label></div><label>Presupuesto<select name="budget">${["Ajustado","Medio","Flexible"].map(value => `<option ${draft.budget === value ? "selected" : ""}>${value}</option>`).join("")}</select></label><label>Alergias o restricciones<input name="restrictions" value="${esc(draft.restrictions || "")}" placeholder="Ej.: sin lactosa, vegetariano"/></label><label>Comidas o ingredientes que no querés<input name="dislikes" value="${esc(draft.dislikes || "")}" placeholder="Ej.: pescado, lentejas"/></label><p class="warning">Si tenés una condición médica, embarazo, alergias importantes o antecedentes de trastornos alimentarios, el plan debe revisarlo un profesional.</p>`;
  if (step === 4) { const selected = draft.missionTitles || missionTemplates.slice(0, 6).map(item => item.title); return `<div class="assessment-intro"><small>MISIONES OBLIGATORIAS</small><h2>Elegí qué querés sostener.</h2><p>Seleccioná entre 4 y 15. Cada misión tiene su propia progresión. El Sistema agregará otras 3 más difíciles cada día.</p></div><div class="selection-count"><b id="mission-count">${selected.length}</b><span>seleccionadas</span></div><div class="mission-choices large-choices">${missionTemplates.map(item => `<label><input type="checkbox" name="missionTitles" value="${esc(item.title)}" ${selected.includes(item.title) ? "checked" : ""}/><span><b>${esc(item.title)}</b><small>${item.target} ${esc(item.unit)} · +${item.xp} XP</small></span></label>`).join("")}</div>`; }
  return `<div class="assessment-intro"><small>MODO DEL CICLO</small><h2>Elegí el nivel de compromiso.</h2><p>Los dos modos conservan progresión, recompensas y penalizaciones limitadas.</p></div><div class="mode-cards"><label><input type="radio" name="mode" value="flexible" ${(draft.mode || "flexible") === "flexible" ? "checked" : ""}/><span><i>AJUSTABLE</i><b>Modo flexible</b><p>Podés cambiar misiones, ejercicios y comidas cuando tu realidad lo requiera.</p></span></label><label><input type="radio" name="mode" value="intensive" ${draft.mode === "intensive" ? "checked" : ""}/><span><i>30 DÍAS</i><b>Modo intensivo</b><p>Al activar el plan, sus misiones y estructura quedan bloqueadas durante el ciclo.</p></span></label></div><p class="health-note">Las penalizaciones restan una cantidad limitada de XP y pueden proponer una recuperación física segura. Nunca se usan para castigar comida, dolor, lesión o enfermedad.</p>`;
}

function assessmentView() {
  const step = Math.max(0, state.onboarding.step);
  return `<section class="assessment-screen"><header><button class="brand static"><span>G30</span><div><b>SISTEMA</b><small>EVALUACIÓN INICIAL</small></div></button><span>PASO ${step + 1} DE ${onboardingSteps.length}</span></header><div class="stepper">${onboardingSteps.map((item, index) => `<i class="${index <= step ? "active" : ""}"><span>${index < step ? "✓" : index + 1}</span><small>${esc(item.label)}</small></i>`).join("")}</div><form id="assessment-form" class="assessment-card">${assessmentForm(step)}<footer><button type="button" class="secondary" id="assessment-back">← ATRÁS</button><button class="primary">${step === onboardingSteps.length - 1 ? "GENERAR MI PLAN" : "CONTINUAR →"}</button></footer></form></section>`;
}

function saveAssessmentStep(form, step) {
  const fd = new FormData(form); const patch = {};
  if (step === 0) Object.assign(patch, { displayName: fd.get("displayName"), age: Number(fd.get("age")), height: Number(fd.get("height")), weight: Number(fd.get("weight")), goal: fd.get("goal") });
  if (step === 1) Object.assign(patch, { workActivity: fd.get("value"), sleepHours: Number(fd.get("sleepHours")), dailyTime: fd.get("dailyTime"), stress: Number(fd.get("stress")) });
  if (step === 2) Object.assign(patch, { experience: fd.get("value"), trainingDays: Number(fd.get("trainingDays")), place: fd.get("place"), equipment: fd.get("equipment"), limitations: fd.get("limitations") });
  if (step === 3) Object.assign(patch, { mealCount: Number(fd.get("mealCount")), cookingTime: fd.get("cookingTime"), budget: fd.get("budget"), restrictions: fd.get("restrictions"), dislikes: fd.get("dislikes") });
  if (step === 4) { patch.missionTitles = fd.getAll("missionTitles"); if (patch.missionTitles.length < 4 || patch.missionTitles.length > 15) throw new Error("Elegí entre 4 y 15 misiones."); }
  if (step === 5) patch.mode = fd.get("mode");
  saveDraft(patch);
}

function planPreviewView() {
  const draft = state.planDraft; if (!draft) return assessmentView();
  return `<section class="preview-screen"><header class="preview-title"><small>PLAN GENERADO · TODAVÍA NO ESTÁ ACTIVO</small><h1>Este es tu Plan G30.</h1><p>Revisalo sin apuro. Podés volver a la evaluación o reemplazar ejercicios y comidas antes de comenzar.</p></header>
    <article class="preview-summary"><span><b>${draft.missions.length}</b>misiones obligatorias</span><span><b>+3</b>del Sistema por día</span><span><b>${draft.routine.length}</b>entrenamientos semanales</span><span><b>7</b>días de comidas</span></article>
    <details open><summary><span>01</span><div><b>Misiones que vas a cumplir</b><small>Se pueden editar por día en modo flexible</small></div></summary><div class="detail-body"><div class="preview-list">${draft.missions.map(mission => `<div><span><b>${esc(mission.title)}</b><small>${mission.target} ${esc(mission.unit)} · nivel 1</small></span><strong>+${mission.xp} XP</strong></div>`).join("")}</div><button class="secondary" data-edit-step="4">CAMBIAR SELECCIÓN</button></div></details>
    <details open><summary><span>02</span><div><b>Rutina de entrenamiento</b><small>Cada ejercicio se puede reemplazar</small></div></summary><div class="detail-body"><div class="routine-grid">${draft.routine.map((day, dayIndex) => routineCard(day, dayIndex, true)).join("")}</div><button class="secondary" data-edit-step="2">CAMBIAR DISPONIBILIDAD</button></div></details>
    <details><summary><span>03</span><div><b>Plan de alimentación</b><small>Recetas simples con ingredientes y preparación</small></div></summary><div class="detail-body"><div class="week-preview">${draft.nutrition.map((day, dayIndex) => `<article><h3>${day.day}</h3>${day.mealIds.map((id, mealIndex) => { const meal = mealById(id); return `<div><span><small>${esc(meal.type)}</small><b>${esc(meal.name)}</b></span><button data-draft-meal="${dayIndex}:${mealIndex}">REEMPLAZAR</button></div>`; }).join("")}</article>`).join("")}</div><button class="secondary" data-edit-step="3">CAMBIAR PREFERENCIAS</button></div></details>
    <div class="activation-panel"><div><small>MODO ${draft.mode === "intensive" ? "INTENSIVO" : "FLEXIBLE"}</small><h2>¿Listo para empezar?</h2><p>Al confirmar se crea el día 1, aparecen tus misiones y se habilitan los registros.</p></div><div><button class="secondary" data-edit-step="0">REVISAR RESPUESTAS</button><button class="primary large" id="confirm-plan">COMENZAR PLAN</button></div></div></section>`;
}

function routineCard(day, dayIndex, preview = false) {
  return `<article class="day-card"><header><small>${esc(day.day)}</small><h3>${esc(day.title)}</h3></header><ol>${day.exercises.map((row, exerciseIndex) => { const exercise = exerciseById(row.exerciseId); return `<li><span><b>${esc(exercise?.name || row.exerciseId)}</b><small>${esc(exercise?.cue || "")}</small></span><strong>${row.sets} × ${esc(row.reps)}</strong>${preview ? `<button class="replace-icon" data-draft-exercise="${dayIndex}:${exerciseIndex}" title="Reemplazar">↻</button>` : ""}</li>`; }).join("")}</ol>${preview ? "" : `<button class="secondary" data-workout="${dayIndex}">REGISTRAR SESIÓN</button>`}</article>`;
}

function missionCard(mission) {
  return `<article class="mission-card ${mission.source} ${isDone(mission) ? "done" : ""}"><button class="check" data-complete="${mission.id}" aria-label="Completar ${esc(mission.title)}">${isDone(mission) ? "✓" : ""}</button><div><header><h3>${esc(mission.title)}</h3>${mission.source === "system" ? "<span>SISTEMA</span>" : `<span>NIVEL ${mission.level || 1}</span>`}</header><p>${esc(mission.description || `${mission.target} ${mission.unit}`)}</p><footer><b>${esc(mission.skill || mission.category)}</b><small>${isDone(mission) ? "Completada hoy" : `${mission.progress || 0} / ${mission.target} ${esc(mission.unit)}`}</small></footer></div><strong class="xp">+${mission.xp}<small> XP</small></strong>${mission.source === "user" ? `<button class="edit" data-edit-mission="${mission.id}" aria-label="Editar misión">⋮</button>` : ""}</article>`;
}

function homeView() {
  const p = progress(); const system = p.daily.filter(m => m.source === "system"); const mandatory = p.daily.filter(m => m.source === "user");
  const activePenalties = state.penalties.filter(item => !item.completed);
  const reset = new Date(); reset.setHours(24, 0, 0, 0); const remaining = reset - new Date(); const countdown = `${String(Math.floor(remaining / 3600000)).padStart(2,"0")}:${String(Math.floor(remaining % 3600000 / 60000)).padStart(2,"0")}`;
  return `<section class="view home-view"><article class="hero-card"><img src="${asset("hero-awakening.webp")}" alt="Figura frente a un portal de energía"/><div class="hero-copy"><small>SISTEMA G30 · DÍA ${state.profile.planDay}</small><h1>Hoy decidís si avanzás.</h1><p>${esc(state.profile.displayName)}, tus misiones son la prioridad. No hace falta un día perfecto: hace falta registrar lo que sí hiciste.</p><div class="hero-stats"><span><b>${state.profile.level}</b>NIVEL · ${state.profile.rank}</span><span><b>${state.profile.xp}</b>XP TOTAL</span><span><b>${p.percent}%</b>HOY</span><span><b>${countdown}</b>REINICIO</span></div></div></article>
    ${activePenalties.map(item => `<article class="penalty"><b>PENALIZACIÓN ACTIVA</b><span><strong>${esc(item.title)}</strong><small>${esc(item.description)} · −${item.xpLoss} XP ya aplicado</small></span><button class="secondary" data-penalty="${item.id}">COMPLETAR</button></article>`).join("")}
    <div class="mission-priority"><div class="section-heading"><div><small>PRIORIDAD DEL PROGRAMA</small><h2>Misiones obligatorias</h2></div><div><b>${mandatory.filter(isDone).length} / ${mandatory.length}</b><button class="mini-button" data-modal="mission">+ AGREGAR</button></div></div><div class="mission-list">${mandatory.map(missionCard).join("")}</div></div>
    <div class="section-heading"><div><small>MÁS DIFÍCILES · CAMBIAN CADA DÍA</small><h2>Misiones del Sistema</h2></div><b>${system.filter(isDone).length} / ${system.length}</b></div><div class="mission-list">${system.map(missionCard).join("")}</div>
    <div class="quick-grid"><button data-view-target="plan"><span>▦</span><b>Plan de hoy</b><small>Rutina y alimentación</small></button><button data-modal="notebook"><span>□</span><b>Cuaderno</b><small>Notas, diario y recordatorios</small></button><button data-modal="close-day"><span>✓</span><b>Cerrar el día</b><small>Balance y continuidad</small></button></div></section>`;
}

function trainingContent() {
  if (!fullAccess()) return lockedContent("La rutina de entrenamiento");
  const selected = Math.min(state.ui.selectedTraining || 0, state.plan.routine.length - 1);
  const day = state.plan.routine[selected]; if (!day) return `<div class="empty-state"><b>No hay sesiones todavía.</b><p>Importá una rutina armada por tus profesionales o generá nuevamente el plan.</p><button class="secondary" data-modal="import-routine">IMPORTAR RUTINA</button></div>`;
  return `<div class="week-tabs">${state.plan.routine.map((item, index) => `<button class="${index === selected ? "active" : ""}" data-training-day="${index}"><b>${esc(item.day.slice(0,3))}</b><small>${esc(item.title)}</small></button>`).join("")}</div><div class="training-session"><header><div><small>SESIÓN ${selected + 1}</small><h2>${esc(day.title)}</h2></div><button class="secondary" data-modal="import-routine">+ RUTINA PROPIA</button></header>${day.exercises.map((row, exerciseIndex) => { const ex = exerciseById(row.exerciseId); const previous = findPreviousSet(row.exerciseId); return `<article class="exercise-row"><span class="exercise-number">${String(exerciseIndex + 1).padStart(2,"0")}</span><div><h3>${esc(ex?.name || row.exerciseId)}</h3><p>${esc(ex?.cue || "")}</p><small>${previous ? `Anterior: ${previous.weight || 0} kg × ${previous.reps || "–"}` : "Primera referencia"}</small></div><strong>${row.sets} × ${esc(row.reps)}</strong><button data-edit-exercise="${selected}:${exerciseIndex}">CAMBIAR</button></article>`; }).join("")}<button class="primary large full" data-workout="${selected}">INICIAR Y REGISTRAR SESIÓN</button></div>`;
}

function findPreviousSet(exerciseId) {
  for (const sessionItem of state.workoutSessions) { const found = sessionItem.sets?.find(set => (set.exerciseId || set.exercise_slug) === exerciseId); if (found) return found; }
  return null;
}

function nutritionContent() {
  if (!fullAccess()) return lockedContent("El plan de alimentación");
  const selected = Math.min(state.ui.selectedNutrition ?? dayNumber() - 1, 6); const day = state.plan.nutrition[selected];
  if (!day) return `<div class="empty-state"><b>No hay menú generado.</b><p>Volvé a generar el plan desde tu perfil.</p></div>`;
  const dayMeals = day.mealIds.map(mealById).filter(Boolean); const totals = dayMeals.reduce((sum, meal) => ({ kcal: sum.kcal + meal.kcal, protein: sum.protein + meal.protein, carbs: sum.carbs + meal.carbs, fats: sum.fats + meal.fats }), { kcal:0, protein:0, carbs:0, fats:0 });
  return `<p class="health-note">Porciones orientativas, no una prescripción médica. Ajustalas según hambre, progreso y criterio profesional. Revisá alergias antes de cocinar.</p><div class="week-tabs seven">${state.plan.nutrition.map((item,index) => `<button class="${index === selected ? "active" : ""}" data-nutrition-day="${index}"><b>${esc(item.day.slice(0,3))}</b></button>`).join("")}</div><div class="macro-strip"><span><b>${totals.kcal}</b>kcal</span><span><b>${totals.protein} g</b>proteína</span><span><b>${totals.carbs} g</b>carbohidratos</span><span><b>${totals.fats} g</b>grasas</span></div><div class="meal-grid">${dayMeals.map((meal, mealIndex) => { const logged = state.mealLogs.some(log => log.mealId === meal.id && log.date === today()); return `<article class="meal-card ${logged ? "logged" : ""}"><small>${esc(meal.type)}</small><h3>${esc(meal.name)}</h3><div><span>${meal.kcal} kcal</span><span>${meal.protein} g proteína</span></div><ul>${meal.ingredients.slice(0,3).map(item => `<li>${esc(item)}</li>`).join("")}</ul><button class="secondary" data-meal-detail="${selected}:${mealIndex}">${logged ? "VER RECETA · REGISTRADA ✓" : "VER RECETA Y REGISTRAR"}</button></article>`; }).join("")}</div>`;
}

function lockedContent(name) { return `<article class="locked"><b>${name} está disponible con Premium</b><p>La versión gratuita mantiene misiones ilimitadas con anuncios. Premium desbloquea rutina, alimentación y elimina anuncios.</p><button class="primary" data-view-target="tienda">VER PREMIUM · USD 1,99/MES</button></article>`; }

function planView() {
  return `<section class="view"><header class="page-title"><small>CICLO ACTIVO · MODO ${state.profile.mode === "intensive" ? "INTENSIVO" : "FLEXIBLE"}</small><h1>Plan G30</h1><p>Entrenamiento, nutrición y misiones en una sola pantalla, organizados en secciones comprimibles.</p></header><details open><summary><span>01</span><div><b>Misiones obligatorias</b><small>${state.missions.filter(m => m.source === "user").length} misiones con progresión propia</small></div><i>⌄</i></summary><div class="detail-body"><div class="compact-missions">${state.missions.filter(m => m.source === "user").map(m => `<div><span><b>${esc(m.title)}</b><small>Nivel ${m.level} · ${m.weekdays.length} días por semana</small></span><strong>${m.target} ${esc(m.unit)}</strong></div>`).join("")}</div><button class="secondary" data-modal="mission">AGREGAR MISIÓN</button></div></details><details open><summary><span>02</span><div><b>Entrenamiento</b><small>${fullAccess() ? `${state.plan.routine.length} sesiones por semana` : "Premium"}</small></div><i>⌄</i></summary><div class="detail-body">${trainingContent()}</div></details><details><summary><span>03</span><div><b>Alimentación</b><small>${fullAccess() ? "7 días · comidas simples" : "Premium"}</small></div><i>⌄</i></summary><div class="detail-body">${nutritionContent()}</div></details></section>`;
}

function academyView() {
  const completed = state.academy.completed.length; const total = academyCourses.reduce((sum, course) => sum + course.lessons.length, 0);
  return `<section class="view"><header class="page-title"><small>CONOCIMIENTO APLICABLE · ${completed}/${total} CLASES</small><h1>Academia</h1><p>Clases detalladas para aprender en serio. No dan XP: el conocimiento vale por lo que cambia en tus decisiones.</p></header><article class="academy-hero"><img src="${asset("academy-archive.webp")}" alt="Archivo futurista de conocimiento"/><div><small>CLASE RECOMENDADA · 18 MIN</small><h2>Esfuerzo y repeticiones en reserva</h2><p>Aprendé cuándo una serie es útil y cómo progresar sin entrenar al fallo siempre.</p><button class="primary" data-lesson="fuerza-base:0">COMENZAR CLASE</button></div></article><p class="daily-limit">PLAN GRATUITO: 1 clase nueva por día · Las clases ya completadas se pueden releer.</p><div class="course-grid">${academyCourses.map(course => `<article class="course"><img src="${asset(course.image)}" alt=""/><div><small>${course.lessons.length} CLASES</small><h3>${esc(course.title)}</h3><p>${esc(course.subtitle)}</p><div class="lesson-links">${course.lessons.map((lesson,index) => `<button data-lesson="${course.id}:${index}" class="${state.academy.completed.includes(`${course.id}:${index}`) ? "complete" : ""}">${state.academy.completed.includes(`${course.id}:${index}`) ? "✓" : index + 1} ${esc(lesson.title)}${lesson.exclusive ? " · EXCLUSIVA" : ""}</button>`).join("")}</div></div></article>`).join("")}</div></section>`;
}

function storeView() {
  return `<section class="view"><header class="page-title"><small>MONEDAS DISPONIBLES · ${state.profile.coins}</small><h1>Tienda</h1><p>Las monedas desbloquean contenido y cosméticos. Nunca compran XP, rachas ni una ventaja competitiva.</p></header><article class="premium-card"><div><small>G30 PREMIUM</small><h2>Rutina + alimentación<br/>sin anuncios</h2><p>Misiones gratuitas ilimitadas. El cobro real se habilitará sólo al conectar Stripe y validar compras en el servidor.</p></div><div><strong>USD 1,99</strong><span>/ mes</span><button class="primary" disabled>PAGO AÚN NO CONECTADO</button></div></article><div class="store-grid">${storeItems.map(item => { const owned = state.economy.owned.includes(item.id); const locked = state.profile.level < item.level; return `<article><small>${esc(item.type)} · NIVEL ${item.level}</small><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p><button class="secondary" data-purchase="${item.id}" ${owned ? "disabled" : ""}>${owned ? "ADQUIRIDO" : locked ? `BLOQUEADO · NIVEL ${item.level}` : `${item.cost} MONEDAS`}</button></article>`; }).join("")}</div><div class="fair"><b>REGLA DE JUEGO LIMPIO</b><p>No se puede comprar XP, rangos, rachas, resultados de Arena ni puestos en el ranking.</p></div></section>`;
}

function profileView() {
  const initials = (state.profile.displayName || "G30").slice(0,2).toUpperCase(); const avatar = state.profile.avatar ? `<img src="${state.profile.avatar}" alt="Avatar"/>` : esc(initials);
  const last14 = Array.from({length:14}, (_, index) => { const value=new Date(Date.now()-(13-index)*86400000); const date=`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`; const review = state.dailyReviews.find(item => item.date === date); return { date, review }; });
  return `<section class="view"><article class="profile-card"><label class="avatar ${state.profile.avatarFrame || ""}">${avatar}<input id="avatar-upload" type="file" accept="image/png,image/jpeg,image/webp"/><small>CAMBIAR</small></label><div><small>RANGO ${state.profile.rank} · NIVEL ${state.profile.level}</small><h1>${esc(state.profile.displayName)}</h1><p>${session ? esc(session.user.email) : "Perfil local · los datos quedan en este dispositivo"}</p></div><button class="secondary" data-modal="auth">${session ? "CUENTA" : "SINCRONIZAR"}</button></article><div class="stat-grid"><article><small>XP TOTAL</small><b>${state.profile.xp}</b></article><article><small>RACHA</small><b>${state.profile.streak} días</b></article><article><small>MEJOR RACHA</small><b>${state.profile.bestStreak}</b></article><article><small>MONEDAS</small><b>${state.profile.coins}</b></article></div><article class="profile-section"><div class="section-heading"><div><small>ÚLTIMOS 14 DÍAS</small><h2>Constancia</h2></div></div><div class="consistency">${last14.map(item => `<span class="${item.review ? item.review.completed === item.review.total ? "perfect" : "partial" : ""}" title="${item.date}">${new Date(`${item.date}T12:00:00`).toLocaleDateString("es",{weekday:"narrow"})}</span>`).join("")}</div></article><article class="profile-section"><h2>Atributos y habilidades</h2><div class="attributes">${attributes.map(attribute => `<div style="--attribute:${attribute.color}"><h3>${attribute.name}</h3>${attribute.skills.map(name => `<span><b>${esc(name)}</b><small>Nivel ${state.skills[name]?.level || 1}</small><i><em style="width:${Math.min(100,(state.skills[name]?.xp || 0)%250/2.5)}%"></em></i></span>`).join("")}</div>`).join("")}</div></article><article class="profile-section"><h2>Logros</h2><div class="achievement-grid">${achievements.map(item => `<div class="${state.achievements.includes(item.id) ? "unlocked" : ""}"><b>${state.achievements.includes(item.id) ? "◆" : "◇"} ${esc(item.title)}</b><small>${esc(item.description)} · ${item.coins} monedas</small></div>`).join("")}</div></article><article class="profile-section"><h2>Historial reciente</h2>${state.workoutSessions.length ? state.workoutSessions.slice(0,5).map(item => `<div class="history"><span><b>${esc(item.title)}</b><small>${esc(item.date)}</small></span><strong>${item.durationMinutes || 0} min</strong></div>`).join("") : "<p>Todavía no registraste entrenamientos.</p>"}</article><article class="profile-section settings"><h2>Datos y cuenta</h2><div class="settings-actions"><button class="secondary" data-modal="notebook">ABRIR CUADERNO</button><button class="secondary" id="export-data">EXPORTAR DATOS</button><button class="danger-button" id="reset-local">REINICIAR APLICACIÓN</button></div></article></section>`;
}

function render() {
  if (!state.onboarding.completed) {
    document.querySelector("#app").innerHTML = state.planDraft && state.onboarding.step >= onboardingSteps.length ? planPreviewView() : state.onboarding.step < 0 ? welcomeView() : assessmentView();
    bindOnboardingEvents(); return;
  }
  const views = { inicio: homeView, plan: planView, academia: academyView, tienda: storeView, perfil: profileView };
  document.querySelector("#app").innerHTML = `<div class="ambient"></div><header class="topbar"><button class="brand" data-view-target="inicio"><span>G30</span><div><b>SISTEMA</b><small>${backend.configured ? (session ? "NUBE ACTIVA" : "CONECTAR CUENTA") : "MODO LOCAL"}</small></div></button><div class="top-resources"><span>◆ ${state.profile.coins}</span><button class="account" data-modal="auth">${session ? esc(state.profile.displayName) : "INICIAR SESIÓN"}</button></div></header><main>${views[currentView]()}</main><div class="floating"><button data-modal="assistant">✦<small>ASISTENTE</small></button><button data-modal="arena">⚔<small>ARENA</small></button></div><nav class="bottom-nav">${[["inicio","⌂","Inicio"],["plan","▣","Plan G30"],["academia","◇","Academia"],["tienda","✦","Tienda"],["perfil","●","Perfil"]].map(([id,icon,label]) => `<button class="${currentView === id ? "active" : ""}" data-view-target="${id}"><span>${icon}</span><small>${label}</small></button>`).join("")}</nav>`;
  bindEvents();
}

function bindOnboardingEvents() {
  const start = document.querySelector("#start-evaluation"); if (start) start.onclick = () => { state.onboarding.step = 0; saveLocalState(state); render(); };
  const form = document.querySelector("#assessment-form"); if (form) {
    const range = form.querySelector('[name="stress"]'); if (range) range.oninput = () => document.querySelector("#stress-value").textContent = `${range.value}/10`;
    form.querySelectorAll('[name="missionTitles"]').forEach(input => input.onchange = () => document.querySelector("#mission-count").textContent = form.querySelectorAll('[name="missionTitles"]:checked').length);
    form.onsubmit = event => { event.preventDefault(); try { const step = state.onboarding.step; saveAssessmentStep(form, step); if (step === onboardingSteps.length - 1) { savePlanDraft(state, getDraft()); state.onboarding.step = onboardingSteps.length; saveLocalState(state); } else { state.onboarding.step += 1; saveLocalState(state); } render(); scrollTo(0,0); } catch (error) { toast(error.message, true); } };
    document.querySelector("#assessment-back").onclick = () => { state.onboarding.step = Math.max(-1, state.onboarding.step - 1); saveLocalState(state); render(); };
  }
  document.querySelectorAll("[data-edit-step]").forEach(button => button.onclick = () => { state.onboarding.step = Number(button.dataset.editStep); state.planDraft = null; saveLocalState(state); render(); scrollTo(0,0); });
  document.querySelectorAll("[data-draft-exercise]").forEach(button => button.onclick = () => { const [day,index] = button.dataset.draftExercise.split(":").map(Number); replaceDraftExercise(state,day,index); render(); });
  document.querySelectorAll("[data-draft-meal]").forEach(button => button.onclick = () => { const [day,index] = button.dataset.draftMeal.split(":").map(Number); replaceDraftMeal(state,day,index); render(); });
  const confirmButton = document.querySelector("#confirm-plan"); if (confirmButton) confirmButton.onclick = () => { confirmLocalPlan(state); currentView = "inicio"; render(); toast("Plan G30 activado · Día 1"); };
}

function modalShell(title, body, wide = false) {
  document.querySelector("#modal-root").innerHTML = `<div class="modal-backdrop"><section class="modal ${wide ? "wide" : ""}"><header><div><small>SISTEMA G30</small><h2>${title}</h2></div><button data-close>×</button></header><div class="modal-body">${body}</div></section></div>`;
  document.querySelector("[data-close]").onclick = closeModal;
  document.querySelector(".modal-backdrop").addEventListener("click", event => { if (event.target.classList.contains("modal-backdrop")) closeModal(); });
}
function closeModal() { document.querySelector("#modal-root").innerHTML = ""; }

function openModal(type, payload) {
  if (type === "auth") return authModal(); if (type === "mission") return missionModal(payload); if (type === "notebook") return notebookModal(payload); if (type === "close-day") return closeDayModal(); if (type === "arena") return arenaModal(); if (type === "assistant") return assistantModal(); if (type === "import-routine") return importRoutineModal();
}

function authModal() {
  if (!backend.configured) return modalShell("Conectar backend", `<div class="empty-state"><b>La aplicación ya funciona en este dispositivo.</b><p>Para sincronizar entre dispositivos, creá un proyecto de Supabase, ejecutá las migraciones y completá <code>.env.local</code>. La guía está en <code>docs/INSTALACION_SUPABASE.md</code>.</p></div>`);
  if (session) { modalShell("Tu cuenta", `<p>Sesión activa como <b>${esc(session.user.email)}</b>.</p><button class="danger-button" id="sign-out">CERRAR SESIÓN</button>`); document.querySelector("#sign-out").onclick = async () => { await backend.signOut(); session = null; closeModal(); render(); }; return; }
  modalShell("Ingresar o registrarte", `<form id="auth-form" class="form"><label>Nombre<input name="name" autocomplete="name"/></label><label>Email<input name="email" type="email" autocomplete="email" required/></label><label>Contraseña<input name="password" type="password" minlength="8" required/></label><div class="form-actions"><button class="secondary" type="button" id="register">CREAR CUENTA</button><button class="primary">INGRESAR</button></div></form>`);
  const form = document.querySelector("#auth-form"); form.onsubmit = async event => { event.preventDefault(); await runAuth(() => backend.signIn(form.email.value, form.password.value)); }; document.querySelector("#register").onclick = () => runAuth(() => backend.signUp(form.email.value, form.password.value, form.name.value || state.profile.displayName));
}
async function runAuth(action) { try { await action(); session = await backend.session(); if (session) await loadCloud(); closeModal(); render(); toast("Cuenta conectada"); } catch (error) { toast(error.message, true); } }

function missionModal(id) {
  const mission = state.missions.find(item => item.id === id);
  if (state.profile.mode === "intensive") return modalShell("Plan bloqueado", `<div class="empty-state"><b>Modo intensivo activo</b><p>Las misiones no pueden cambiarse durante este ciclo de 30 días.</p></div>`);
  modalShell(mission ? "Editar misión" : "Nueva misión obligatoria", `<form id="mission-form" class="form"><label>Título<input name="title" required maxlength="80" value="${esc(mission?.title || "")}"/></label><label>Descripción<input name="description" maxlength="160" value="${esc(mission?.description || "")}"/></label><div class="form-row"><label>Objetivo<input name="target" type="number" min="1" value="${mission?.target || 1}"/></label><label>Unidad<input name="unit" value="${esc(mission?.unit || "vez")}"/></label></div><label>Categoría<select name="category">${["entrenamiento","nutrición","disciplina","enfoque","recuperación","movilidad","resistencia","trabajo","finanzas","social"].map(value => `<option ${mission?.category === value ? "selected" : ""}>${value}</option>`).join("")}</select></label><fieldset><legend>Días de la semana</legend><div class="days">${["L","M","X","J","V","S","D"].map((label,index) => `<label><input type="checkbox" name="day" value="${index+1}" ${(mission?.weekdays || [1,2,3,4,5,6,7]).includes(index+1) ? "checked" : ""}/><span>${label}</span></label>`).join("")}</div></fieldset><button class="primary">${mission ? "GUARDAR CAMBIOS" : "CREAR MISIÓN"}</button></form>`);
  document.querySelector("#mission-form").onsubmit = event => { event.preventDefault(); const form = event.currentTarget; const fd = new FormData(form); const data = { title:fd.get("title"),description:fd.get("description"),target:Number(fd.get("target")),unit:fd.get("unit"),category:fd.get("category"),weekdays:fd.getAll("day").map(Number) }; try { mission ? updateMissionLocal(state,id,data) : addMissionLocal(state,data); closeModal(); render(); toast("Misión guardada"); } catch(error) { toast(error.message,true); } };
}

function workoutModal(index) {
  const day = state.plan.routine[index]; if (!day) return;
  modalShell(`Registrar ${esc(day.title)}`, `<form id="workout-form" class="form workout-log"><div class="form-row"><label>Duración (min)<input name="duration" type="number" min="1" value="45"/></label><label>Esfuerzo general (RPE)<input name="sessionRpe" type="number" min="1" max="10" value="7"/></label></div>${day.exercises.map((row,exerciseIndex) => { const ex = exerciseById(row.exerciseId); const previous = findPreviousSet(row.exerciseId); return `<fieldset><legend>${exerciseIndex + 1}. ${esc(ex?.name)}</legend><p>${esc(ex?.cue)}</p>${Array.from({length:row.sets},(_,setIndex) => `<div class="set-row"><b>Serie ${setIndex+1}</b><label>kg<input name="weight-${exerciseIndex}-${setIndex}" type="number" min="0" step=".5" value="${previous?.weight || previous?.weight_kg || 0}"/></label><label>reps<input name="reps-${exerciseIndex}-${setIndex}" type="number" min="0" value="${Number(previous?.reps) || parseInt(row.reps) || 8}"/></label><label>RPE<input name="rpe-${exerciseIndex}-${setIndex}" type="number" min="1" max="10" value="${previous?.rpe || 7}"/></label><label class="done-set"><input name="done-${exerciseIndex}-${setIndex}" type="checkbox" checked/><span>✓</span></label></div>`).join("")}</fieldset>`; }).join("")}<label>Notas<textarea name="notes" placeholder="Técnica, molestias, energía, próxima meta..."></textarea></label><button class="primary">GUARDAR ENTRENAMIENTO</button></form>`, true);
  document.querySelector("#workout-form").onsubmit = async event => { event.preventDefault(); const fd = new FormData(event.currentTarget); const sets = day.exercises.flatMap((row,exerciseIndex) => Array.from({length:row.sets},(_,setIndex) => ({ exerciseId:row.exerciseId,setNumber:setIndex+1,weight:Number(fd.get(`weight-${exerciseIndex}-${setIndex}`))||0,reps:Number(fd.get(`reps-${exerciseIndex}-${setIndex}`))||0,rpe:Number(fd.get(`rpe-${exerciseIndex}-${setIndex}`))||null,done:fd.has(`done-${exerciseIndex}-${setIndex}`) }))); const payload={title:day.title,dayIndex:index,durationMinutes:Number(fd.get("duration")),sessionRpe:Number(fd.get("sessionRpe")),notes:fd.get("notes"),sets}; logWorkoutLocal(state,payload); try { if(session) await backend.logWorkout(payload); } catch(error) { toast(`Guardado local; no se pudo sincronizar: ${error.message}`,true); } closeModal(); render(); toast("Entrenamiento y marcas guardados"); };
}

function editExerciseModal(spec) { const [dayIndex,exerciseIndex] = spec.split(":").map(Number); const current = state.plan.routine[dayIndex].exercises[exerciseIndex]; modalShell("Cambiar ejercicio", `<form id="exercise-change" class="form"><label>Ejercicio<select name="exerciseId">${exercises.map(item => `<option value="${item.id}" ${item.id === current.exerciseId ? "selected" : ""}>${esc(item.name)} · ${esc(item.equipment)}</option>`).join("")}</select></label><p class="warning">Elegí una alternativa que no cause dolor y respete las indicaciones de tus profesionales.</p><button class="primary">GUARDAR CAMBIO</button></form>`); document.querySelector("#exercise-change").onsubmit = event => { event.preventDefault(); try { replacePlanExercise(state,dayIndex,exerciseIndex,new FormData(event.currentTarget).get("exerciseId")); closeModal(); render(); } catch(error) { toast(error.message,true); } }; }

function mealDetailModal(spec) { const [dayIndex,mealIndex] = spec.split(":").map(Number); const id = state.plan.nutrition[dayIndex].mealIds[mealIndex]; const meal = mealById(id); const alternatives = meals.filter(item => item.type === meal.type && item.id !== meal.id); const logged = state.mealLogs.some(item => item.mealId === id && item.date === today()); modalShell(esc(meal.name), `<article class="recipe"><div class="macro-strip"><span><b>${meal.kcal}</b>kcal</span><span><b>${meal.protein} g</b>proteína</span><span><b>${meal.carbs} g</b>carbohidratos</span><span><b>${meal.fats} g</b>grasas</span></div><h3>Ingredientes</h3><ul>${meal.ingredients.map(item => `<li>${esc(item)}</li>`).join("")}</ul><h3>Preparación</h3><ol>${meal.steps.map(item => `<li>${esc(item)}</li>`).join("")}</ol><p class="health-note">Las cantidades son orientativas. Revisá ingredientes y contaminación cruzada si tenés alergias.</p><form id="meal-actions" class="form"><label>Reemplazar por<select name="replacement"><option value="">Conservar esta comida</option>${alternatives.map(item => `<option value="${item.id}">${esc(item.name)}</option>`).join("")}</select></label><button class="secondary" id="replace-meal" type="button">GUARDAR REEMPLAZO</button><button class="primary" ${logged ? "disabled" : ""}>${logged ? "COMIDA REGISTRADA ✓" : "REGISTRAR COMO COMPLETADA"}</button></form></article>`); const form = document.querySelector("#meal-actions"); document.querySelector("#replace-meal").onclick = () => { const replacement = form.replacement.value; if (!replacement) return toast("Elegí una alternativa",true); try { replacePlanMeal(state,dayIndex,mealIndex,replacement); closeModal(); render(); toast("Comida reemplazada"); } catch(error) { toast(error.message,true); } }; form.onsubmit = async event => { event.preventDefault(); logMealLocal(state,id); try { if(session) await backend.logMeal(id,meal.name); } catch(error) { toast(`Guardado local; no se pudo sincronizar: ${error.message}`,true); } closeModal(); render(); toast("Comida registrada"); }; }

function importRoutineModal() { if (state.profile.mode === "intensive") return modalShell("Rutina bloqueada",`<div class="empty-state"><b>Modo intensivo activo</b><p>La estructura no puede cambiarse durante este ciclo.</p></div>`); modalShell("Importar rutina profesional", `<form id="routine-import" class="form"><p>Agregá una sesión ya armada por tu entrenador. Un ejercicio por línea con este formato: <code>Nombre | series | repeticiones</code>.</p><label>Nombre de la sesión<input name="title" required placeholder="Ej.: Torso profesional"/></label><label>Ejercicios<textarea name="rows" required placeholder="Press con mancuernas | 4 | 8\nRemo a una mano | 4 | 10"></textarea></label><button class="primary">AGREGAR A MI RUTINA</button></form>`); document.querySelector("#routine-import").onsubmit = event => { event.preventDefault(); const fd = new FormData(event.currentTarget); const rows = String(fd.get("rows")).split("\n").map(line => line.split("|").map(part => part.trim())).filter(parts => parts[0]).map(parts => { const match = exercises.find(ex => ex.name.toLowerCase() === parts[0].toLowerCase()) || exercises.find(ex => ex.name.toLowerCase().includes(parts[0].toLowerCase())); return { exerciseId:match?.id || "sentadilla",sets:Math.max(1,Number(parts[1])||3),reps:parts[2]||"8–12",restSeconds:90 }; }); importRoutineLocal(state,fd.get("title"),rows); closeModal(); render(); toast("Rutina personal agregada"); }; }

function notebookModal(noteId) {
  const note = state.notes.find(item => item.id === noteId) || (!noteId && state.notes[0]);
  modalShell("Cuaderno libre", `<div class="notebook-layout"><aside><button class="secondary" id="new-note">+ NUEVA HOJA</button>${state.notes.map(item => `<button data-note="${item.id}" class="${note?.id === item.id ? "active" : ""}"><b>${esc(item.title)}</b><small>${new Date(item.updatedAt).toLocaleDateString("es")}</small></button>`).join("") || "<p>Todavía no hay hojas.</p>"}</aside><form id="note-form" class="form"><label>Título<input name="title" value="${esc(note?.title || "")}" placeholder="Recordatorio, diario, ideas..."/></label><label>Escribí lo que quieras<textarea class="notebook" name="body" placeholder="Este espacio es tuyo...">${esc(note?.body || "")}</textarea></label><p class="privacy">El cuaderno es privado. El Asistente local no lee estas notas.</p><button class="primary">GUARDAR HOJA</button></form></div>`, true);
  document.querySelectorAll("[data-note]").forEach(button => button.onclick = () => notebookModal(button.dataset.note));
  document.querySelector("#new-note").onclick = () => { closeModal(); modalShell("Nueva hoja", `<form id="note-form" class="form"><label>Título<input name="title" placeholder="Nueva hoja"/></label><label>Contenido<textarea class="notebook" name="body"></textarea></label><button class="primary">GUARDAR HOJA</button></form>`); bindNoteForm(null); };
  bindNoteForm(note);
}
function bindNoteForm(note) { const form = document.querySelector("#note-form"); if (!form) return; form.onsubmit = async event => { event.preventDefault(); const fd = new FormData(event.currentTarget); const data={id:note?.id,title:fd.get("title"),body:fd.get("body")}; const saved=saveNoteLocal(state,data); try { if(session){const cloud=await backend.saveNote(data);saved.id=cloud.id;saveLocalState(state);} } catch(error) { toast(`Guardado local; no se pudo sincronizar: ${error.message}`,true); } closeModal(); render(); toast("Cuaderno guardado"); }; }

function closeDayModal() { const p = progress(); modalShell("Cierre del día", `<form id="close-form" class="form"><div class="closing-score"><b>${p.done} / ${p.total}</b><span>misiones completadas</span></div><label>¿Qué funcionó hoy?<textarea name="reflection" placeholder="Una idea concreta para repetir mañana"></textarea></label><p class="warning">Si quedaron misiones obligatorias sin cumplir, el Sistema restará hasta 50 XP y creará una recuperación para mañana. No cierres el día si todavía vas a completar tareas.</p><button class="primary">CONFIRMAR CIERRE</button></form>`); document.querySelector("#close-form").onsubmit = async event => { event.preventDefault(); const reflection=new FormData(event.currentTarget).get("reflection"); const result = closeDayLocal(state,reflection); try { if(session) await backend.closeDay(reflection); } catch(error) { toast(`Cierre local guardado; no se pudo sincronizar: ${error.message}`,true); } closeModal(); render(); toast(result.missed ? `Día cerrado · ${result.missed} misiones pendientes` : "Día perfecto · racha actualizada"); }; }

function lessonModal(spec) {
  const [courseId,indexRaw] = spec.split(":"); const index = Number(indexRaw); const course = academyCourses.find(item => item.id === courseId); const lesson = course?.lessons[index]; if (!lesson) return;
  const completed = state.academy.completed.includes(spec); if (lesson.exclusive && !state.economy.owned.includes("recipe-pack-1") && !state.profile.premium) { modalShell("Clase exclusiva", `<div class="empty-state"><b>Contenido exclusivo de la Academia</b><p>Desbloqueá el paquete de recetas con monedas en la Tienda o accedé con Premium.</p><button class="primary" data-view-store>IR A LA TIENDA</button></div>`); document.querySelector("[data-view-store]").onclick=()=>{closeModal();currentView="tienda";render();}; return; }
  modalShell(esc(lesson.title), `<article class="lesson"><small>${lesson.minutes} MIN · ${esc(course.title)} ${completed ? "· COMPLETADA" : ""}</small>${lesson.sections.map(section => `<section><h3>${esc(section.h)}</h3><p>${esc(section.p)}</p></section>`).join("")}<form id="lesson-quiz" class="form"><fieldset><legend>Comprobación rápida</legend><h3>${esc(lesson.quiz.q)}</h3><div class="quiz-options">${lesson.quiz.options.map((answer,answerIndex) => `<label><input type="radio" name="answer" value="${answerIndex}"/><span>${esc(answer)}</span></label>`).join("")}</div></fieldset><button class="primary">${completed ? "VOLVER A COMPROBAR" : "COMPLETAR CLASE"}</button></form></article>`, true);
  document.querySelector("#lesson-quiz").onsubmit = event => { event.preventDefault(); const answer = Number(new FormData(event.currentTarget).get("answer")); if (answer !== lesson.quiz.correct) return toast("Esa respuesta no es correcta. Revisá la clase.",true); try { completeLessonLocal(state,courseId,index); closeModal(); render(); toast("Clase completada · conocimiento, no XP"); } catch(error) { toast(error.message,true); } };
}

function arenaModal() {
  const p = progress(); const localRanking = [{name:state.profile.displayName,score:state.arena.wins*100+state.arena.bestScore*10},{name:"Sistema E",score:180},{name:"Sistema D",score:420}].sort((a,b)=>b.score-a.score);
  modalShell("Arena y Mazmorras", `<div class="arena-tabs"><article class="duel-card"><small>ARENA PERSONAL</small><h3>Duelo de voluntad</h3><p>Elegí cuánta energía invertir. Tu racha agrega hasta 3 puntos. El ganador se muestra de forma explícita.</p><form id="arena-duel" class="form"><label>Poder elegido: <b id="power-output">5</b><input name="power" type="range" min="1" max="10" value="5"/></label><button class="primary">ENFRENTAR AL SISTEMA</button></form><div id="duel-result"></div></article><article class="dungeon"><img src="${asset("dungeon-gate.webp")}" alt="Portal de una mazmorra"/><div><small>MAZMORRA DIARIA · RANGO ${state.profile.rank}</small><h3>La Puerta de la Constancia</h3><p>Requisito: completar al menos 80% de las misiones de hoy. Progreso: ${p.percent}%.</p><button class="primary" id="complete-dungeon" ${p.percent < 80 ? "disabled" : ""}>ENTRAR · RECOMPENSA 30 MONEDAS</button></div></article><section class="ranking"><h3>Ranking local</h3>${localRanking.map((row,index) => `<div><b>#${index+1} ${esc(row.name)}</b><strong>${row.score} pts</strong></div>`).join("")}<p>El ranking público y las guerras entre gremios necesitan cuentas y validación del servidor. Este ranking local ya registra tus resultados reales.</p><form id="guild-form" class="form"><label>Nombre de tu gremio<input name="guild" maxlength="40" value="${esc(state.arena.guildName)}" placeholder="Creá tu gremio"/></label><button class="secondary">GUARDAR GREMIO LOCAL</button></form></section></div>`, true);
  const form = document.querySelector("#arena-duel"); form.power.oninput = () => document.querySelector("#power-output").textContent = form.power.value; form.onsubmit = async event => { event.preventDefault(); try { const result = session ? await backend.playArena(form.power.value) : arenaDuelLocal(state,form.power.value); if(session) await loadCloud(); document.querySelector("#duel-result").innerHTML = `<div class="duel-result ${result.won ? "won" : "lost"}"><b>${result.result}</b><span>VOS ${result.user} — ${result.system} SISTEMA</span>${result.won ? "<small>+12 monedas</small>" : ""}</div>`; } catch(error) { toast(error.message,true); } };
  document.querySelector("#complete-dungeon").onclick = async () => { try { const result = completeDungeonLocal(state); if(session) await backend.completeDungeon(); closeModal(); render(); toast(`Mazmorra superada · +${result.reward} monedas`); } catch(error) { toast(error.message,true); } };
  document.querySelector("#guild-form").onsubmit = event => { event.preventDefault(); setGuildLocal(state,new FormData(event.currentTarget).get("guild")); toast("Gremio local guardado"); };
}

function assistantModal() { const advice = assistantRules(state); modalShell("Asistente G30", `<div class="assistant-card"><span>✦</span><small>RECOMENDACIÓN BASADA EN TUS REGISTROS</small><h3>${esc(advice.title)}</h3><p>${esc(advice.text)}</p><button class="primary" id="assistant-action">IR A LA ACCIÓN</button></div><p class="privacy">Esta versión usa reglas locales verificables. No inventa diagnósticos ni modifica tu plan sin pedir confirmación.</p>`); document.querySelector("#assistant-action").onclick = () => { closeModal(); if (advice.action === "close-day") return closeDayModal(); currentView = advice.action === "evaluation" ? "perfil" : advice.action; render(); }; }

async function resizeAvatar(file) { if (!/^image\/(png|jpeg|webp)$/.test(file.type) || file.size > 8_000_000) throw new Error("Usá una imagen PNG, JPG o WebP de menos de 8 MB."); const image = await createImageBitmap(file); const size = Math.min(512,Math.max(image.width,image.height)); const canvas = document.createElement("canvas"); canvas.width = size; canvas.height = size; const ctx = canvas.getContext("2d"); const scale = Math.max(size/image.width,size/image.height); const width=image.width*scale,height=image.height*scale; ctx.drawImage(image,(size-width)/2,(size-height)/2,width,height); return canvas.toDataURL("image/webp",.82); }

function exportData() { const blob = new Blob([JSON.stringify(state,null,2)],{type:"application/json"}); const link=document.createElement("a"); link.href=URL.createObjectURL(blob); link.download=`g30-backup-${today()}.json`; link.click(); setTimeout(()=>URL.revokeObjectURL(link.href),1000); }

async function completeMission(id) { const mission = state.missions.find(item => item.id === id); const wasDone = isDone(mission); try { completeMissionLocal(state,id); render(); if (session) await backend.completeMission(id); toast(wasDone ? "Misión reabierta" : `Misión completada · ${mission.skill || mission.category} progresa`); } catch(error) { toast(error.message,true); } }

function bindEvents() {
  document.querySelectorAll("[data-view-target]").forEach(button => button.onclick = () => { currentView=button.dataset.viewTarget; render(); scrollTo({top:0,behavior:"smooth"}); });
  document.querySelectorAll("[data-modal]").forEach(button => button.onclick = () => openModal(button.dataset.modal));
  document.querySelectorAll("[data-complete]").forEach(button => button.onclick = () => completeMission(button.dataset.complete));
  document.querySelectorAll("[data-edit-mission]").forEach(button => button.onclick = () => missionModal(button.dataset.editMission));
  document.querySelectorAll("[data-workout]").forEach(button => button.onclick = () => workoutModal(Number(button.dataset.workout)));
  document.querySelectorAll("[data-edit-exercise]").forEach(button => button.onclick = () => editExerciseModal(button.dataset.editExercise));
  document.querySelectorAll("[data-meal-detail]").forEach(button => button.onclick = () => mealDetailModal(button.dataset.mealDetail));
  document.querySelectorAll("[data-lesson]").forEach(button => button.onclick = () => lessonModal(button.dataset.lesson));
  document.querySelectorAll("[data-training-day]").forEach(button => button.onclick = () => { state.ui.selectedTraining=Number(button.dataset.trainingDay); saveLocalState(state); render(); });
  document.querySelectorAll("[data-nutrition-day]").forEach(button => button.onclick = () => { state.ui.selectedNutrition=Number(button.dataset.nutritionDay); saveLocalState(state); render(); });
  document.querySelectorAll("[data-penalty]").forEach(button => button.onclick = () => { completePenaltyLocal(state,button.dataset.penalty); render(); toast("Recuperación completada"); });
  document.querySelectorAll("[data-purchase]").forEach(button => button.onclick = async () => { try { const item=storeItems.find(entry=>entry.id===button.dataset.purchase); purchaseLocal(state,item.id); if(session) await backend.purchaseStoreItem(item.id,item.cost,item.level); render(); toast("Contenido desbloqueado"); } catch(error) { toast(error.message,true); } });
  const avatarInput=document.querySelector("#avatar-upload"); if(avatarInput) avatarInput.onchange=async()=>{try{const data=await resizeAvatar(avatarInput.files[0]);saveAvatarLocal(state,data);render();toast("Avatar actualizado");}catch(error){toast(error.message,true);}};
  const exporter=document.querySelector("#export-data"); if(exporter) exporter.onclick=exportData;
  const reset=document.querySelector("#reset-local"); if(reset) reset.onclick=()=>{if(confirm("¿Reiniciar la aplicación y borrar todos los datos locales? Exportalos antes si querés conservarlos.")){state=resetLocalState();currentView="inicio";render();toast("Aplicación reiniciada");}};
}

async function loadCloud() {
  let cloud=await backend.loadDashboard(); if(!cloud)return;
  if(!cloud.plan && state.plan.active && state.evaluation?.missionTitles?.length){await backend.generatePlan(state.evaluation);cloud=await backend.loadDashboard();}
  state.profile={...state.profile,displayName:cloud.profile.display_name,avatar:cloud.profile.avatar_url||state.profile.avatar,avatarFrame:cloud.profile.avatar_frame||state.profile.avatarFrame,xp:cloud.profile.xp,level:cloud.profile.level,rank:cloud.profile.rank||state.profile.rank,streak:cloud.profile.streak,bestStreak:cloud.profile.best_streak||state.profile.bestStreak,coins:cloud.profile.coins??state.profile.coins,mode:cloud.profile.mode,premium:cloud.profile.is_premium};
  if(cloud.plan){state.plan={...state.plan,active:cloud.plan.active,startDate:cloud.plan.started_on,routine:cloud.plan.training_plan?.days||state.plan.routine,nutrition:cloud.plan.nutrition_plan?.days||state.plan.nutrition};}
  if(cloud.missions?.length) state.missions=cloud.missions.map(m=>({id:m.id,title:m.title,description:m.description,category:m.category,target:Number(m.target_value),unit:m.unit,xp:m.reward_xp,source:m.source,level:m.progression_level,weekdays:m.weekdays,progress:0,completedOn:(m.mission_completions||[]).map(c=>c.completed_on),order:m.sort_order}));
  state.notes=cloud.notes?.map(n=>({id:n.id,title:n.title,body:n.body,updatedAt:n.updated_at}))||state.notes; state.workoutSessions=cloud.workoutSessions||state.workoutSessions; state.mealLogs=cloud.mealLogs?.map(m=>({id:m.id,date:m.logged_at.slice(0,10),mealId:m.recipe_slug}))||state.mealLogs; state.onboarding.completed=Boolean(state.plan.active); saveLocalState(state);
  for(const skill of cloud.skills||[]) state.skills[skill.skill_key]={xp:skill.xp,level:skill.level};
  if(cloud.purchases) state.economy.owned=cloud.purchases.map(item=>item.item_key);
  if(cloud.arenaScores){state.arena.history=cloud.arenaScores.map(item=>({date:item.played_at.slice(0,10),result:item.result,user:item.score}));state.arena.wins=cloud.arenaScores.filter(item=>item.result==="victory").length;state.arena.losses=cloud.arenaScores.filter(item=>item.result==="defeat").length;}
  if(cloud.dungeonRuns){state.dungeons.history=cloud.dungeonRuns.map(item=>({date:item.run_date,completion:item.completion_percent,reward:item.coins_awarded}));state.dungeons.completed=cloud.dungeonRuns.length;}
  if(cloud.dailyReviews) state.dailyReviews=cloud.dailyReviews.map(item=>({date:item.review_date,completed:item.completed_count,total:item.total_count,reflection:item.reflection}));
  if(cloud.penalties) state.penalties=cloud.penalties.map(item=>({id:item.id,sourceDate:item.source_date,title:item.title,description:item.description,xpLoss:item.xp_loss,completed:item.completed}));
  if(cloud.achievements) state.achievements=cloud.achievements.map(item=>item.achievement_key);
  saveLocalState(state);
}

async function boot(){try{session=await backend.session();if(session)await loadCloud();backend.onAuthChange(async next=>{session=next;if(next){try{await loadCloud();}catch(error){toast(error.message,true);}}render();});}catch(error){toast(`Backend no disponible: ${error.message}`,true);}render();if("serviceWorker" in navigator&&import.meta.env.PROD)navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`).catch(()=>{});}
boot();
